apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  labels:
    app: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      # volumes:
      #   - name: shared-data
      #     persistentVolumeClaim:
      #       claimName: data-claim
      containers:
        - name: ping-pong
          image: turtvaiz/ping-pong:2.1
          # volumeMounts:
          #   - name: shared-data
          #     mountPath: /app/files