apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: turtvaiz/todo-app:2.10-5
          volumeMounts:
            - mountPath: /app/cache
              name: img-vol
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: BACKEND_URL
            - name: PICSUM_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: PICSUM_URL
      volumes:
        - name: img-vol
          emptyDir: {}
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: turtvaiz/todo-app:be-2.10-5
          envFrom:
            - secretRef:
                name: psql-auth
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-stset
spec:
  serviceName: pg-svc
  replicas: 1
  selector:
    matchLabels:
      app: pg-app
  template:
    metadata:
      labels:
        app: pg-app
    spec:
      containers:
        - name: pg
          image: postgres:alpine
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /data
          envFrom:
            - secretRef:
                name: psql-auth
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi