apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/secret.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
images:
  - name: PROJECT/IMAGE
    newName: turtvaiz/todo-app:2.10-5
  - name: BE_PROJECT/IMAGE
    newName: turtvaiz/todo-app:be-2.10-5