[project]
name = "todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "psycopg2>=2.9.11",
    "requests>=2.32.5",
    "sqlmodel>=0.0.31",
]
