name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: hy-kubernetes
  IMAGE_BE: todo-app-be
  IMAGE_FE: todo-app-fe
  SERVICE: todo-svc
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: sirit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker "$REGISTRY"
        
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name : 'Form the image name'
        run: echo "IMAGE_TAG_BE=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_BE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name : 'Form the image name'
        run: echo "IMAGE_TAG_FE=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_FE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: docker build --tag $IMAGE_TAG_BE todo-app -f todo-app/back.Dockerfile

      - name: Build front
        run: docker build --tag $IMAGE_TAG_FE todo-app -f todo-app/front.Dockerfile

      - name: Publish
        run: docker push $IMAGE_TAG_BE
      - name: Publish
        run: docker push $IMAGE_TAG_FE
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      - name: Deploy
        working-directory: "todo-app"
        run: |-
          kustomize edit set image PROJECT/IMAGE=$IMAGE_TAG_BE
          kustomize edit set image BE_PROJECT/IMAGE=$IMAGE_TAG_FE
          kustomize build todo-app | kubectl apply -f -
          kubectl rollout status deployment $SERVICE
          kubectl get services -o wide